### ISSUE TITLE
Copy only needed files from fmriprep folder

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#1010]
It seems this is the problem: https://github.com/cpp-lln-lab/bidspm/blob/05d92e9ebcf854e42d2cd12db55495479704239c/bidspm.m#L271

The copy to the bidspm-preproc will only be done during smooth if the output dir does not already exist.

Possibility A (easy and slow): copy files for every smooth even if output dir is there... slow because you may copy files several times but at least you make sure that the files are there.

Possibility B: only copy the needed files.

Can you check if only keeping `copy(args);` and removing the if block solves it?

If so I would suggest to open a PR with this small change and open a separate issue to see how to implement possibility B.

_Originally posted by @Remi-Gau in https://github.com/cpp-lln-lab/bidspm/issues/1006#issuecomment-1531518822_

**Comment by Remi-Gau** [comment]
This will need a bids.matlab fix because copying to derivatives with bidspm unzipps the nifti files and removes the nii.gz file.
So when copying again bids.matlab only checks to see if there is a .nii.gz file to decide whether it should copy again: since there is none it starts the copying / unzipping process again.

**Comment by Remi-Gau** [comment]
this should now be fixed at the bids matlab level
