### ISSUE TITLE
[BUG] `bidsCopyInputFolder` does not care about session within ` opt.bidsFilterFile`

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/bidspm#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

To set a session to query and get the data only for that session

### Current Behavior

Querying a sub with more than 1 session (eg 8), It grabs all the data corresponding to anat and to the tasks selected independently of the session in 

```matlab
opt.bidsFilterFile.t1w.ses = '001';
opt.bidsFilterFile.bold.ses = '001';
```

I think it is just missing a line with for eg bold like `filter.ses = opt.bidsFilterFile.bold.ses`

### Environment

```markdown
- OS: mac os
- Matlab: 2017b
- SPM: 'SPM12 (7487)'
```

### Branch

```markdown
- branch: dev 
- commit: c344dbb31af8c7c3c79b6bfb80527d708e8c940d
```

### Anything else?

CPP_SPM developers are awesome!

**Comment by Remi-Gau** [comment]
just to be sure, it does work if you put that in `opt.query.ses` ?

**Comment by Remi-Gau** [comment]
sligthtly related to #408

**Comment by marcobarilari** [comment]
>Actually opt.bidsFilterFile appears no where in the bidsCopyInputFolder...

you right....

**Comment by Remi-Gau** [comment]
In the next major release this will probably be rewritten to have bidsCopyInputFolder only use bidsFilterFile

**Comment by Remi-Gau** [comment]
probably that it will be easier to handle this only via the `bidspm(..., 'action', copy)` as it accepts a `bids_filter_file` argument already)

**Comment by Remi-Gau** [comment]
working on this in #1275.

it looks fixed

<details>
<summary>input data</summary>
<pre>
tests/data/bidspm-raw
├── dataset_description.json
├── layout.mat
├── participants.json
├── participants.tsv
├── sub-01
│   ├── ses-01
│   │   ├── anat
│   │   │   ├── sub-01_ses-01_inv-1_MP2RAGE.json
│   │   │   ├── sub-01_ses-01_inv-1_MP2RAGE.nii
│   │   │   ├── sub-01_ses-01_inv-2_MP2RAGE.json
│   │   │   ├── sub-01_ses-01_inv-2_MP2RAGE.nii
│   │   │   ├── sub-01_ses-01_T1w.nii
│   │   │   └── sub-01_ses-01_UNIT1.nii
│   │   ├── fmap
│   │   │   ├── sub-01_ses-01_run-1_magnitude1.nii
│   │   │   ├── sub-01_ses-01_run-1_magnitude2.nii
│   │   │   ├── sub-01_ses-01_run-1_phasediff.json
│   │   │   ├── sub-01_ses-01_run-1_phasediff.nii
│   │   │   ├── sub-01_ses-01_run-2_magnitude1.nii
│   │   │   ├── sub-01_ses-01_run-2_magnitude2.nii
│   │   │   ├── sub-01_ses-01_run-2_phasediff.json
│   │   │   └── sub-01_ses-01_run-2_phasediff.nii
│   │   └── func
│   │       ├── sub-01_ses-01_task-vislocalizer_events.tsv
│   │       ├── sub-01_ses-01_task-vislocalizer_part-mag_bold.nii
│   │       ├── sub-01_ses-01_task-vislocalizer_part-phase_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_acq-1p60mm_run-1_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_acq-1p60mm_run-1_events.tsv
│   │       ├── sub-01_ses-01_task-vismotion_acq-1p60mm_run-2_events.tsv
│   │       ├── sub-01_ses-01_task-vismotion_run-1_events.tsv
│   │       ├── sub-01_ses-01_task-vismotion_run-1_part-mag_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_run-1_part-phase_bold.nii
│   │       ├── sub-01_ses-01_task-vismotion_run-2_events.tsv
│   │       ├── sub-01_ses-01_task-vismotion_run-2_part-mag_bold.nii
│   │       └── sub-01_ses-01_task-vismotion_run-2_part-phase_bold.nii
│   └── ses-02
│       ├── anat
│       │   ├── sub-01_ses-02_inv-1_MP2RAGE.json
│       │   ├── sub-01_ses-02_inv-1_MP2RAGE.nii
│       │   ├── sub-01_ses-02_inv-2_MP2RAGE.json
│       │   ├── sub-01_ses-02_inv-2_MP2RAGE.nii
│       │   ├── sub-01_ses-02_T1w.nii
│       │   └── sub-01_ses-02_UNIT1.nii
│       ├── fmap
│       │   ├── sub-01_ses-02_run-1_magnitude1.nii
│       │   ├── sub-01_ses-02_run-1_magnitude2.nii
│       │   ├── sub-01_ses-02_run-1_phasediff.json
│       │   ├── sub-01_ses-02_run-1_phasediff.nii
│       │   ├── sub-01_ses-02_run-2_magnitude1.nii
│       │   ├── sub-01_ses-02_run-2_magnitude2.nii
│       │   ├── sub-01_ses-02_run-2_phasediff.json
│       │   └── sub-01_ses-02_run-2_phasediff.nii
│       └── func
│           ├── sub-01_ses-02_task-rest_bold.nii
│           ├── sub-01_ses-02_task-vislocalizer_events.tsv
│           ├── sub-01_ses-02_task-vislocalizer_part-mag_bold.nii
│           ├── sub-01_ses-02_task-vislocalizer_part-phase_bold.nii
│           ├── sub-01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│           ├── sub-01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│           ├── sub-01_ses-02_task-vismotion_acq-1p60mm_run-1_bold.nii
│           ├── sub-01_ses-02_task-vismotion_acq-1p60mm_run-1_events.tsv
│           ├── sub-01_ses-02_task-vismotion_acq-1p60mm_run-2_events.tsv
│           ├── sub-01_ses-02_task-vismotion_run-1_events.tsv
│           ├── sub-01_ses-02_task-vismotion_run-1_part-mag_bold.nii
│           ├── sub-01_ses-02_task-vismotion_run-1_part-phase_bold.nii
│           ├── sub-01_ses-02_task-vismotion_run-2_events.tsv
│           ├── sub-01_ses-02_task-vismotion_run-2_part-mag_bold.nii
│           └── sub-01_ses-02_task-vismotion_run-2_part-phase_bold.nii
├── sub-blind01
│   ├── ses-01
│   │   ├── anat
│   │   │   ├── sub-blind01_ses-01_inv-1_MP2RAGE.json
│   │   │   ├── sub-blind01_ses-01_inv-1_MP2RAGE.nii
│   │   │   ├── sub-blind01_ses-01_inv-2_MP2RAGE.json
│   │   │   ├── sub-blind01_ses-01_inv-2_MP2RAGE.nii
│   │   │   ├── sub-blind01_ses-01_T1w.nii
│   │   │   └── sub-blind01_ses-01_UNIT1.nii
│   │   ├── fmap
│   │   │   ├── sub-blind01_ses-01_run-1_magnitude1.nii
│   │   │   ├── sub-blind01_ses-01_run-1_magnitude2.nii
│   │   │   ├── sub-blind01_ses-01_run-1_phasediff.json
│   │   │   ├── sub-blind01_ses-01_run-1_phasediff.nii
│   │   │   ├── sub-blind01_ses-01_run-2_magnitude1.nii
│   │   │   ├── sub-blind01_ses-01_run-2_magnitude2.nii
│   │   │   ├── sub-blind01_ses-01_run-2_phasediff.json
│   │   │   └── sub-blind01_ses-01_run-2_phasediff.nii
│   │   └── func
│   │       ├── sub-blind01_ses-01_task-vislocalizer_events.tsv
│   │       ├── sub-blind01_ses-01_task-vislocalizer_part-mag_bold.nii
│   │       ├── sub-blind01_ses-01_task-vislocalizer_part-phase_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_acq-1p60mm_run-1_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_acq-1p60mm_run-1_events.tsv
│   │       ├── sub-blind01_ses-01_task-vismotion_acq-1p60mm_run-2_events.tsv
│   │       ├── sub-blind01_ses-01_task-vismotion_run-1_events.tsv
│   │       ├── sub-blind01_ses-01_task-vismotion_run-1_part-mag_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_run-1_part-phase_bold.nii
│   │       ├── sub-blind01_ses-01_task-vismotion_run-2_events.tsv
│   │       ├── sub-blind01_ses-01_task-vismotion_run-2_part-mag_bold.nii
│   │       └── sub-blind01_ses-01_task-vismotion_run-2_part-phase_bold.nii
│   └── ses-02
│       ├── anat
│       │   ├── sub-blind01_ses-02_inv-1_MP2RAGE.json
│       │   ├── sub-blind01_ses-02_inv-1_MP2RAGE.nii
│       │   ├── sub-blind01_ses-02_inv-2_MP2RAGE.json
│       │   ├── sub-blind01_ses-02_inv-2_MP2RAGE.nii
│       │   ├── sub-blind01_ses-02_T1w.nii
│       │   └── sub-blind01_ses-02_UNIT1.nii
│       ├── fmap
│       │   ├── sub-blind01_ses-02_run-1_magnitude1.nii
│       │   ├── sub-blind01_ses-02_run-1_magnitude2.nii
│       │   ├── sub-blind01_ses-02_run-1_phasediff.json
│       │   ├── sub-blind01_ses-02_run-1_phasediff.nii
│       │   ├── sub-blind01_ses-02_run-2_magnitude1.nii
│       │   ├── sub-blind01_ses-02_run-2_magnitude2.nii
│       │   ├── sub-blind01_ses-02_run-2_phasediff.json
│       │   └── sub-blind01_ses-02_run-2_phasediff.nii
│       └── func
│           ├── sub-blind01_ses-02_task-rest_bold.nii
│           ├── sub-blind01_ses-02_task-vislocalizer_events.tsv
│           ├── sub-blind01_ses-02_task-vislocalizer_part-mag_bold.nii
│           ├── sub-blind01_ses-02_task-vislocalizer_part-phase_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_acq-1p60mm_run-1_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_acq-1p60mm_run-1_events.tsv
│           ├── sub-blind01_ses-02_task-vismotion_acq-1p60mm_run-2_events.tsv
│           ├── sub-blind01_ses-02_task-vismotion_run-1_events.tsv
│           ├── sub-blind01_ses-02_task-vismotion_run-1_part-mag_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_run-1_part-phase_bold.nii
│           ├── sub-blind01_ses-02_task-vismotion_run-2_events.tsv
│           ├── sub-blind01_ses-02_task-vismotion_run-2_part-mag_bold.nii
│           └── sub-blind01_ses-02_task-vismotion_run-2_part-phase_bold.nii
├── sub-ctrl01
│   ├── ses-01
│   │   ├── anat
│   │   │   ├── sub-ctrl01_ses-01_inv-1_MP2RAGE.json
│   │   │   ├── sub-ctrl01_ses-01_inv-1_MP2RAGE.nii
│   │   │   ├── sub-ctrl01_ses-01_inv-2_MP2RAGE.json
│   │   │   ├── sub-ctrl01_ses-01_inv-2_MP2RAGE.nii
│   │   │   ├── sub-ctrl01_ses-01_T1w.nii
│   │   │   └── sub-ctrl01_ses-01_UNIT1.nii
│   │   ├── fmap
│   │   │   ├── sub-ctrl01_ses-01_run-1_magnitude1.nii
│   │   │   ├── sub-ctrl01_ses-01_run-1_magnitude2.nii
│   │   │   ├── sub-ctrl01_ses-01_run-1_phasediff.json
│   │   │   ├── sub-ctrl01_ses-01_run-1_phasediff.nii
│   │   │   ├── sub-ctrl01_ses-01_run-2_magnitude1.nii
│   │   │   ├── sub-ctrl01_ses-01_run-2_magnitude2.nii
│   │   │   ├── sub-ctrl01_ses-01_run-2_phasediff.json
│   │   │   └── sub-ctrl01_ses-01_run-2_phasediff.nii
│   │   └── func
│   │       ├── sub-ctrl01_ses-01_task-vislocalizer_events.tsv
│   │       ├── sub-ctrl01_ses-01_task-vislocalizer_part-mag_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vislocalizer_part-phase_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_run-1_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_run-1_events.tsv
│   │       ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_run-2_events.tsv
│   │       ├── sub-ctrl01_ses-01_task-vismotion_run-1_events.tsv
│   │       ├── sub-ctrl01_ses-01_task-vismotion_run-1_part-mag_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_run-1_part-phase_bold.nii
│   │       ├── sub-ctrl01_ses-01_task-vismotion_run-2_events.tsv
│   │       ├── sub-ctrl01_ses-01_task-vismotion_run-2_part-mag_bold.nii
│   │       └── sub-ctrl01_ses-01_task-vismotion_run-2_part-phase_bold.nii
│   └── ses-02
│       ├── anat
│       │   ├── sub-ctrl01_ses-02_inv-1_MP2RAGE.json
│       │   ├── sub-ctrl01_ses-02_inv-1_MP2RAGE.nii
│       │   ├── sub-ctrl01_ses-02_inv-2_MP2RAGE.json
│       │   ├── sub-ctrl01_ses-02_inv-2_MP2RAGE.nii
│       │   ├── sub-ctrl01_ses-02_T1w.nii
│       │   └── sub-ctrl01_ses-02_UNIT1.nii
│       ├── fmap
│       │   ├── sub-ctrl01_ses-02_run-1_magnitude1.nii
│       │   ├── sub-ctrl01_ses-02_run-1_magnitude2.nii
│       │   ├── sub-ctrl01_ses-02_run-1_phasediff.json
│       │   ├── sub-ctrl01_ses-02_run-1_phasediff.nii
│       │   ├── sub-ctrl01_ses-02_run-2_magnitude1.nii
│       │   ├── sub-ctrl01_ses-02_run-2_magnitude2.nii
│       │   ├── sub-ctrl01_ses-02_run-2_phasediff.json
│       │   └── sub-ctrl01_ses-02_run-2_phasediff.nii
│       └── func
│           ├── sub-ctrl01_ses-02_task-rest_bold.nii
│           ├── sub-ctrl01_ses-02_task-vislocalizer_events.tsv
│           ├── sub-ctrl01_ses-02_task-vislocalizer_part-mag_bold.nii
│           ├── sub-ctrl01_ses-02_task-vislocalizer_part-phase_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-1_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_acq-1p60mm_dir-PA_run-2_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_acq-1p60mm_run-1_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_acq-1p60mm_run-1_events.tsv
│           ├── sub-ctrl01_ses-02_task-vismotion_acq-1p60mm_run-2_events.tsv
│           ├── sub-ctrl01_ses-02_task-vismotion_run-1_events.tsv
│           ├── sub-ctrl01_ses-02_task-vismotion_run-1_part-mag_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_run-1_part-phase_bold.nii
│           ├── sub-ctrl01_ses-02_task-vismotion_run-2_events.tsv
│           ├── sub-ctrl01_ses-02_task-vismotion_run-2_part-mag_bold.nii
│           └── sub-ctrl01_ses-02_task-vismotion_run-2_part-phase_bold.nii
├── T1w.json
├── task-rest_bold.json
├── task-vislocalizer_bold.json
└── task-vismotion_bold.json
</pre>
</details>

Script using `bidspm(..., 'action', 'copy')` instead of of the lower level `bidsCopyInputFolder`

```matlab
  inputPath = getTestDataDir('raw');

  outputPath = tempName();

  bidspm(inputPath, outputPath, 'subject', ...
         'action', 'copy', ...
         'participant_label', {'01', 'ctrl01'}, ...
         'task', {'vismotion'}, ...
         'bids_filter_file', struct('anat', struct('modality', 'anat', ...
                                                   'suffix', 'T1w', ...
                                                   'ses', '01'), ...
                                    'bold', struct('modality', 'func', ...
                                                   'suffix', 'events', ...
                                                   'ses', '01')), ...
         'verbosity', 0);
```

```output
└── derivatives
    ├── bidspm-preproc
    │   ├── CHANGES
    │   ├── dataset_description.json
    │   ├── LICENSE
    │   ├── README.md
    │   ├── sub-01
    │   │   └── ses-01
    │   │       ├── anat
    │   │       │   ├── sub-01_ses-01_T1w.json
    │   │       │   └── sub-01_ses-01_T1w.nii
    │   │       └── func
    │   │           ├── sub-01_ses-01_task-vismotion_acq-1p60mm_run-1_events.tsv
    │   │           ├── sub-01_ses-01_task-vismotion_acq-1p60mm_run-2_events.tsv
    │   │           ├── sub-01_ses-01_task-vismotion_run-1_events.tsv
    │   │           └── sub-01_ses-01_task-vismotion_run-2_events.tsv
    │   └── sub-ctrl01
    │       └── ses-01
    │           ├── anat
    │           │   ├── sub-ctrl01_ses-01_T1w.json
    │           │   └── sub-ctrl01_ses-01_T1w.nii
    │           └── func
    │               ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_run-1_events.tsv
    │               ├── sub-ctrl01_ses-01_task-vismotion_acq-1p60mm_run-2_events.tsv
    │               ├── sub-ctrl01_ses-01_task-vismotion_run-1_events.tsv
    │               └── sub-ctrl01_ses-01_task-vismotion_run-2_events.tsv
    └── options
        └── options_task-vismotion_2024-07-09T22-41.json
```
